export const LIBRARY_CATEGORIES = [
  { id: "1", name: "All", value: "" },
  { id: "2", name: "Computer Science", value: "computer-science" },
  { id: "3", name: "Data Structures & Algorithms", value: "data-structures-algorithms" },
  { id: "4", name: "Operating Systems", value: "operating-systems" },
  { id: "5", name: "Networking", value: "networking" },
  { id: "6", name: "Compilers & Interpreters", value: "compilers-interpreters" },
  { id: "7", name: "Computer Architecture", value: "computer-architecture" },
  { id: "8", name: "Programming Languages", value: "programming-languages" },
  { id: "9", name: "JavaScript / TypeScript", value: "javascript-typescript" },
  { id: "10", name: "Python", value: "python" },
  { id: "11", name: "Rust", value: "rust" },
  { id: "12", name: "Go", value: "go" },
  { id: "13", name: "Java", value: "java" },
  { id: "14", name: "C / C++", value: "c-cpp" },
  { id: "15", name: "Functional Programming", value: "functional-programming" },
  { id: "16", name: "Frontend", value: "frontend" },
  { id: "17", name: "Backend", value: "backend" },
  { id: "18", name: "Full Stack", value: "full-stack" },
  { id: "19", name: "APIs & Integrations", value: "apis-integrations" },
  { id: "20", name: "Web Performance", value: "web-performance" },
  { id: "21", name: "Web3 / Blockchain", value: "web3-blockchain" },
  { id: "22", name: "Mobile", value: "mobile" },
  { id: "23", name: "iOS", value: "ios" },
  { id: "24", name: "Android", value: "android" },
  { id: "25", name: "UI/UX Design", value: "ui-ux-design" },
  { id: "26", name: "Design Systems", value: "design-systems" },
  { id: "27", name: "Accessibility", value: "accessibility" },
  { id: "28", name: "System Design", value: "system-design" },
  { id: "29", name: "Software Architecture", value: "software-architecture" },
  { id: "30", name: "Distributed Systems", value: "distributed-systems" },
  { id: "31", name: "Microservices", value: "microservices" },
  { id: "32", name: "Database", value: "database" },
  { id: "33", name: "Data Engineering", value: "data-engineering" },
  { id: "34", name: "Data Science", value: "data-science" },
  { id: "35", name: "Machine Learning", value: "machine-learning" },
  { id: "36", name: "Deep Learning", value: "deep-learning" },
  { id: "37", name: "AI", value: "ai" },
  { id: "38", name: "Cloud", value: "cloud" },
  { id: "39", name: "DevOps", value: "devops" },
  { id: "40", name: "Containers & Kubernetes", value: "containers-kubernetes" },
  { id: "41", name: "Linux / Unix", value: "linux-unix" },
  { id: "42", name: "Observability & Monitoring", value: "observability-monitoring" },
  { id: "43", name: "Site Reliability Engineering", value: "site-reliability-engineering" },
  { id: "44", name: "Cybersecurity", value: "cybersecurity" },
  { id: "45", name: "Cryptography", value: "cryptography" },
  { id: "46", name: "Penetration Testing", value: "penetration-testing" },
  { id: "47", name: "Clean Code", value: "clean-code" },
  { id: "48", name: "Testing & QA", value: "testing-qa" },
  { id: "49", name: "Refactoring", value: "refactoring" },
  { id: "50", name: "Game Development", value: "game-development" },
  { id: "51", name: "Embedded Systems", value: "embedded-systems" },
  { id: "52", name: "IoT", value: "iot" },
  { id: "53", name: "AR / VR", value: "ar-vr" },
  { id: "54", name: "Quantum Computing", value: "quantum-computing" },
  { id: "55", name: "Career & Soft Skills", value: "career-soft-skills" },
  { id: "56", name: "Technical Writing", value: "technical-writing" },
  { id: "57", name: "Product Management", value: "product-management" },
  { id: "58", name: "Agile & Scrum", value: "agile-scrum" },
  { id: "59", name: "Open Source", value: "open-source" },
  { id: "60", name: "Entrepreneurship", value: "entrepreneurship" },
];
